import "./globals.css";
import { Inter } from "next/font/google";
import EditorModeState from "../../context/EditorModeState";
import ThemeModeState from "../../context/ThemeModeState";
import DirectionModeState from "../../context/DirectionModeState";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <DirectionModeState>
      <ThemeModeState>
        <EditorModeState>
          <html lang="en">
            <body className={inter.className}>{children}</body>
          </html>
        </EditorModeState>
      </ThemeModeState>
    </DirectionModeState>
  );
}
