const Data = {
  country: [
    {
      label: "afghanistan",
      type: "country",
      info: "country",
      apply: "'afghanistan' ",
    },
    {
      label: "albania",
      type: "country",
      info: "country",
      apply: "'albania' ",
    },
    {
      label: "argentina",
      type: "country",
      info: "country",
      apply: "'argentina' ",
    },
    {
      label: "australia",
      type: "country",
      info: "country",
      apply: "'australia' ",
    },
    {
      label: "belgium",
      type: "country",
      info: "country",
      apply: "'belgium' ",
    },
    {
      label: "brazil",
      type: "country",
      info: "country",
      apply: "'brazil' ",
    },
    {
      label: "canada",
      type: "country",
      info: "country",
      apply: "'canada' ",
    },
    {
      label: "china",
      type: "country",
      info: "country",
      apply: "'china' ",
    },
    {
      label: "denmark",
      type: "country",
      info: "country",
      apply: "'denmark' ",
    },
    {
      label: "egypt",
      type: "country",
      info: "country",
      apply: "'egypt' ",
    },
    {
      label: "france",
      type: "country",
      info: "country",
      apply: "'france' ",
    },
    {
      label: "germany",
      type: "country",
      info: "country",
      apply: "'germany' ",
    },
    {
      label: "greece",
      type: "country",
      info: "country",
      apply: "'greece' ",
    },
    {
      label: "hungary",
      type: "country",
      info: "country",
      apply: "'hungary' ",
    },
    {
      label: "india",
      type: "country",
      info: "country",
      apply: "'india' ",
    },
    {
      label: "ireland",
      type: "country",
      info: "country",
      apply: "'ireland' ",
    },
    {
      label: "italy",
      type: "country",
      info: "country",
      apply: "'italy' ",
    },
    {
      label: "japan",
      type: "country",
      info: "country",
      apply: "'japan' ",
    },
    {
      label: "kenya",
      type: "country",
      info: "country",
      apply: "'kenya' ",
    },
    {
      label: "lebanon",
      type: "country",
      info: "country",
      apply: "'lebanon' ",
    },
    {
      label: "malaysia",
      type: "country",
      info: "country",
      apply: "'malaysia' ",
    },
    {
      label: "mexico",
      type: "country",
      info: "country",
      apply: "'mexico' ",
    },
    {
      label: "netherlands",
      type: "country",
      info: "country",
      apply: "'netherlands' ",
    },
    {
      label: "new zealand",
      type: "country",
      info: "country",
      apply: "'new zealand' ",
    },
    {
      label: "norway",
      type: "country",
      info: "country",
      apply: "'norway' ",
    },
    {
      label: "pakistan",
      type: "country",
      info: "country",
      apply: "'pakistan' ",
    },
    { label: "peru", type: "country", info: "country", apply: "'peru' " },
    {
      label: "poland",
      type: "country",
      info: "country",
      apply: "'poland' ",
    },
    {
      label: "russia",
      type: "country",
      info: "country",
      apply: "'russia' ",
    },
    {
      label: "saudi arabia",
      type: "country",
      info: "country",
      apply: "'saudi arabia' ",
    },
    {
      label: "spain",
      type: "country",
      info: "country",
      apply: "'spain' ",
    },
    {
      label: "south africa",
      type: "country",
      info: "country",
      apply: "'south africa' ",
    },
    {
      label: "south korea",
      type: "country",
      info: "country",
      apply: "'south korea' ",
    },
    {
      label: "sweden",
      type: "country",
      info: "country",
      apply: "'sweden' ",
    },
    {
      label: "switzerland",
      type: "country",
      info: "country",
      apply: "'switzerland' ",
    },
    {
      label: "thailand",
      type: "country",
      info: "country",
      apply: "'thailand' ",
    },
    {
      label: "turkey",
      type: "country",
      info: "country",
      apply: "'turkey' ",
    },
    {
      label: "united kingdom",
      type: "country",
      info: "country",
      apply: "'united kingdom' ",
    },
    {
      label: "united states",
      type: "country",
      info: "country",
      apply: "'united states' ",
    },
    {
      label: "vietnam",
      type: "country",
      info: "country",
      apply: "'vietnam' ",
    },
  ],
  city: [
    { label: "tokyo", type: "city", info: "city", apply: "'tokyo' " },
    { label: "paris", type: "city", info: "city", apply: "'paris' " },
    { label: "london", type: "city", info: "city", apply: "'london' " },
    {
      label: "new york city",
      type: "city",
      info: "city",
      apply: "'new york city' ",
    },
    { label: "berlin", type: "city", info: "city", apply: "'berlin' " },
    { label: "rome", type: "city", info: "city", apply: "'rome' " },
    { label: "cairo", type: "city", info: "city", apply: "'cairo' " },
    { label: "mumbai", type: "city", info: "city", apply: "'mumbai' " },
    { label: "sydney", type: "city", info: "city", apply: "'sydney' " },
    {
      label: "rio de janeiro",
      type: "city",
      info: "city",
      apply: `'"rio de janeiro"' `,
    },
    {
      label: "cape town",
      type: "city",
      info: "city",
      apply: "'cape town' ",
    },
    {
      label: "istanbul",
      type: "city",
      info: "city",
      apply: "'istanbul' ",
    },
    {
      label: "amsterdam",
      type: "city",
      info: "city",
      apply: "'amsterdam' ",
    },
    { label: "hanoi", type: "city", info: "city", apply: "'hanoi' " },
    { label: "bangkok", type: "city", info: "city", apply: "'bangkok' " },
    {
      label: "barcelona",
      type: "city",
      info: "city",
      apply: "'barcelona' ",
    },
    { label: "moscow", type: "city", info: "city", apply: "'moscow' " },
    { label: "dubai", type: "city", info: "city", apply: "'dubai' " },
    { label: "beijing", type: "city", info: "city", apply: "'beijing' " },
    { label: "rome", type: "city", info: "city", apply: "'rome' " },
    {
      label: "rio de janeiro",
      type: "city",
      info: "city",
      apply: "'rio de janeiro' ",
    },
    {
      label: "cape town",
      type: "city",
      info: "city",
      apply: "'cape town' ",
    },
    {
      label: "istanbul",
      type: "city",
      info: "city",
      apply: "'istanbul' ",
    },
    {
      label: "amsterdam",
      type: "city",
      info: "city",
      apply: "'amsterdam' ",
    },
    { label: "hanoi", type: "city", info: "city", apply: "'hanoi' " },
    { label: "bangkok", type: "city", info: "city", apply: "'bangkok' " },
    {
      label: "barcelona",
      type: "city",
      info: "city",
      apply: "'barcelona' ",
    },
    { label: "moscow", type: "city", info: "city", apply: "'moscow' " },
    { label: "dubai", type: "city", info: "city", apply: "'dubai' " },
    { label: "beijing", type: "city", info: "city", apply: "'beijing' " },
    {
      label: "istanbul",
      type: "city",
      info: "city",
      apply: "'istanbul' ",
    },
    {
      label: "amsterdam",
      type: "city",
      info: "city",
      apply: "'amsterdam' ",
    },
    { label: "hanoi", type: "city", info: "city", apply: "'hanoi' " },
    { label: "bangkok", type: "city", info: "city", apply: "'bangkok' " },
    {
      label: "barcelona",
      type: "city",
      info: "city",
      apply: "'barcelona' ",
    },
    { label: "moscow", type: "city", info: "city", apply: "'moscow' " },
    { label: "dubai", type: "city", info: "city", apply: "'dubai' " },
    { label: "beijing", type: "city", info: "city", apply: "'beijing' " },
    {
      label: "istanbul",
      type: "city",
      info: "city",
      apply: "'istanbul' ",
    },
    {
      label: "amsterdam",
      type: "city",
      info: "city",
      apply: "'amsterdam' ",
    },
    { label: "hanoi", type: "city", info: "city", apply: "'hanoi' " },
    { label: "bangkok", type: "city", info: "city", apply: "'bangkok' " },
    {
      label: "barcelona",
      type: "city",
      info: "city",
      apply: "'barcelona' ",
    },
    { label: "moscow", type: "city", info: "city", apply: "'moscow' " },
    { label: "dubai", type: "city", info: "city", apply: "'dubai' " },
    { label: "beijing", type: "city", info: "city", apply: "'beijing' " },
    {
      label: "istanbul",
      type: "city",
      info: "city",
      apply: "'istanbul' ",
    },
    {
      label: "amsterdam",
      type: "city",
      info: "city",
      apply: "'amsterdam' ",
    },
    { label: "hanoi", type: "city", info: "city", apply: "'hanoi' " },
    { label: "bangkok", type: "city", info: "city", apply: "'bangkok' " },
    {
      label: "barcelona",
      type: "city",
      info: "city",
      apply: "'barcelona' ",
    },
    { label: "moscow", type: "city", info: "city", apply: "'moscow' " },
    { label: "dubai", type: "city", info: "city", apply: "'dubai' " },
    { label: "beijing", type: "city", info: "city", apply: "'beijing' " },
    {
      label: "istanbul",
      type: "city",
      info: "city",
      apply: "'istanbul' ",
    },
    {
      label: "amsterdam",
      type: "city",
      info: "city",
      apply: "'amsterdam' ",
    },
    { label: "hanoi", type: "city", info: "city", apply: "'hanoi' " },
    { label: "bangkok", type: "city", info: "city", apply: "'bangkok' " },
    {
      label: "barcelona",
      type: "city",
      info: "city",
      apply: "'barcelona' ",
    },
    { label: "moscow", type: "city", info: "city", apply: "'moscow' " },
    { label: "dubai", type: "city", info: "city", apply: "'dubai' " },
    { label: "beijing", type: "city", info: "city", apply: "'beijing' " },
    {
      label: "istanbul",
      type: "city",
      info: "city",
      apply: "'istanbul' ",
    },
    {
      label: "amsterdam",
      type: "city",
      info: "city",
      apply: "'amsterdam' ",
    },
    { label: "hanoi", type: "city", info: "city", apply: "'hanoi' " },
    { label: "bangkok", type: "city", info: "city", apply: "'bangkok' " },
    {
      label: "barcelona",
      type: "city",
      info: "city",
      apply: "'barcelona' ",
    },
    { label: "moscow", type: "city", info: "city", apply: "'moscow' " },
    { label: "dubai", type: "city", info: "city", apply: "'dubai' " },
    { label: "beijing", type: "city", info: "city", apply: "'beijing' " },
  ],
  operators: [
    {
      label: "and",
      type: "operatorAnd",
      info: "and",
      apply: "AND ",
    },
    {
      label: "or",
      type: "operatorOr",
      info: "or",
      apply: "OR ",
    },
    {
      label: "not",
      type: "operatorNot",
      info: "not",
      apply: "NOT ",
    },
  ],
  keywords: [
    {
      label: "sprinklr",
      info: "cmx",
      type: "keyword",
      apply: "sprinklr ",
    },
    {
      label: "apple",
      info: "eat",
      type: "keyword",
      apply: "apple ",
    },
    {
      label: "banana",
      apply: "banana ",
      info: "eat",
      type: "keyword",
    },
    {
      label: "cat",
      info: "animal",
      type: "keyword",
      apply: "cat ",
    },
  ],
  advancedOperators: [
    {
      label: "city",
      info: "list name",
      type: "link",
      apply: "city:",
    },
    {
      label: "country",
      info: "list name",
      type: "link",
      apply: "country:",
    },
  ],
};
export default Data;
