const Data = {
  country: [
    {
      label: "afghanistan",
      type: "country",
      detail: "",
      apply: '"afghanistan" ',
    },
    {
      label: "albania",
      type: "country",
      detail: "",
      apply: '"albania" ',
    },
    {
      label: "argentina",
      type: "country",
      detail: "",
      apply: '"argentina" ',
    },
    {
      label: "australia",
      type: "country",
      detail: "",
      apply: '"australia" ',
    },
    {
      label: "belgium",
      type: "country",
      detail: "",
      apply: '"belgium" ',
    },
    { label: "brazil", type: "country", detail: "", apply: '"brazil" ' },
    { label: "canada", type: "country", detail: "", apply: '"canada" ' },
    { label: "china", type: "country", detail: "", apply: '"china" ' },
    {
      label: "denmark",
      type: "country",
      detail: "",
      apply: '"denmark" ',
    },
    { label: "egypt", type: "country", detail: "", apply: '"egypt" ' },
    { label: "france", type: "country", detail: "", apply: '"france" ' },
    {
      label: "germany",
      type: "country",
      detail: "",
      apply: '"germany" ',
    },
    { label: "greece", type: "country", detail: "", apply: '"greece" ' },
    {
      label: "hungary",
      type: "country",
      detail: "",
      apply: '"hungary" ',
    },
    { label: "india", type: "country", detail: "", apply: '"india" ' },
    {
      label: "ireland",
      type: "country",
      detail: "",
      apply: '"ireland" ',
    },
    { label: "italy", type: "country", detail: "", apply: '"italy" ' },
    { label: "japan", type: "country", detail: "", apply: '"japan" ' },
    { label: "kenya", type: "country", detail: "", apply: '"kenya" ' },
    {
      label: "lebanon",
      type: "country",
      detail: "",
      apply: '"lebanon" ',
    },
    {
      label: "malaysia",
      type: "country",
      detail: "",
      apply: '"malaysia" ',
    },
    { label: "mexico", type: "country", detail: "", apply: '"mexico" ' },
    {
      label: "netherlands",
      type: "country",
      detail: "",
      apply: '"netherlands" ',
    },
    {
      label: "new zealand",
      type: "country",
      detail: "",
      apply: '"new zealand" ',
    },
    { label: "norway", type: "country", detail: "", apply: '"norway" ' },
    {
      label: "pakistan",
      type: "country",
      detail: "",
      apply: '"pakistan" ',
    },
    { label: "peru", type: "country", detail: "", apply: '"peru" ' },
    { label: "poland", type: "country", detail: "", apply: '"poland" ' },
    { label: "russia", type: "country", detail: "", apply: '"russia" ' },
    {
      label: "saudi arabia",
      type: "country",
      detail: "",
      apply: '"saudi arabia" ',
    },
    { label: "spain", type: "country", detail: "", apply: '"spain" ' },
    {
      label: "south africa",
      type: "country",
      detail: "",
      apply: '"south africa" ',
    },
    {
      label: "south korea",
      type: "country",
      detail: "",
      apply: '"south korea" ',
    },
    { label: "sweden", type: "country", detail: "", apply: '"sweden" ' },
    {
      label: "switzerland",
      type: "country",
      detail: "",
      apply: '"switzerland" ',
    },
    {
      label: "thailand",
      type: "country",
      detail: "",
      apply: '"thailand" ',
    },
    { label: "turkey", type: "country", detail: "", apply: '"turkey" ' },
    {
      label: "united kingdom",
      type: "country",
      detail: "",
      apply: '"united kingdom" ',
    },
    {
      label: "united states",
      type: "country",
      detail: "",
      apply: '"united states" ',
    },
    {
      label: "vietnam",
      type: "country",
      detail: "",
      apply: '"vietnam" ',
    },
  ],

  city: [
    { label: "tokyo", type: "city", detail: "", apply: '"tokyo" ' },
    { label: "paris", type: "city", detail: "", apply: '"paris" ' },
    { label: "london", type: "city", detail: "", apply: '"london" ' },
    {
      label: "new york city",
      type: "city",
      detail: "",
      apply: '"new york city" ',
    },
    { label: "berlin", type: "city", detail: "", apply: '"berlin" ' },
    { label: "rome", type: "city", detail: "", apply: '"rome" ' },
    { label: "cairo", type: "city", detail: "", apply: '"cairo" ' },
    { label: "mumbai", type: "city", detail: "", apply: '"mumbai" ' },
    { label: "sydney", type: "city", detail: "", apply: '"sydney" ' },
    {
      label: "cape town",
      type: "city",
      detail: "",
      apply: '"cape town" ',
    },
    { label: "istanbul", type: "city", detail: "", apply: '"istanbul" ' },
    {
      label: "amsterdam",
      type: "city",
      detail: "",
      apply: '"amsterdam" ',
    },
    { label: "hanoi", type: "city", detail: "", apply: '"hanoi" ' },
    { label: "bangkok", type: "city", detail: "", apply: '"bangkok" ' },
    {
      label: "barcelona",
      type: "city",
      detail: "",
      apply: '"barcelona" ',
    },
    { label: "moscow", type: "city", detail: "", apply: '"moscow" ' },
    { label: "dubai", type: "city", detail: "", apply: '"dubai" ' },
    { label: "beijing", type: "city", detail: "", apply: '"beijing" ' },
    { label: "rome", type: "city", detail: "", apply: '"rome" ' },
    {
      label: "rio de janeiro",
      type: "city",
      detail: "",
      apply: '"rio de janeiro" ',
    },
    {
      label: "cape town",
      type: "city",
      detail: "",
      apply: '"cape town" ',
    },
    { label: "istanbul", type: "city", detail: "", apply: '"istanbul" ' },
    {
      label: "amsterdam",
      type: "city",
      detail: "",
      apply: '"amsterdam" ',
    },
    { label: "hanoi", type: "city", detail: "", apply: '"hanoi" ' },
    { label: "bangkok", type: "city", detail: "", apply: '"bangkok" ' },
    {
      label: "barcelona",
      type: "city",
      detail: "",
      apply: '"barcelona" ',
    },
    { label: "moscow", type: "city", detail: "", apply: '"moscow" ' },
    { label: "dubai", type: "city", detail: "", apply: '"dubai" ' },
    { label: "beijing", type: "city", detail: "", apply: '"beijing" ' },
    { label: "istanbul", type: "city", detail: "", apply: '"istanbul" ' },
    {
      label: "amsterdam",
      type: "city",
      detail: "",
      apply: '"amsterdam" ',
    },
    { label: "hanoi", type: "city", detail: "", apply: '"hanoi" ' },
    { label: "bangkok", type: "city", detail: "", apply: '"bangkok" ' },
    {
      label: "barcelona",
      type: "city",
      detail: "",
      apply: '"barcelona" ',
    },
    { label: "moscow", type: "city", detail: "", apply: '"moscow" ' },
    { label: "dubai", type: "city", detail: "", apply: '"dubai" ' },
    { label: "beijing", type: "city", detail: "", apply: '"beijing" ' },
    { label: "istanbul", type: "city", detail: "", apply: '"istanbul" ' },
    {
      label: "amsterdam",
      type: "city",
      detail: "",
      apply: '"amsterdam" ',
    },
    { label: "hanoi", type: "city", detail: "", apply: '"hanoi" ' },
    { label: "bangkok", type: "city", detail: "", apply: '"bangkok" ' },
    {
      label: "barcelona",
      type: "city",
      detail: "",
      apply: '"barcelona" ',
    },
    { label: "moscow", type: "city", detail: "", apply: '"moscow" ' },
    { label: "dubai", type: "city", detail: "", apply: '"dubai" ' },
    { label: "beijing", type: "city", detail: "", apply: '"beijing" ' },
    { label: "istanbul", type: "city", detail: "", apply: '"istanbul" ' },
    {
      label: "amsterdam",
      type: "city",
      detail: "",
      apply: '"amsterdam" ',
    },
    { label: "hanoi", type: "city", detail: "", apply: '"hanoi" ' },
    { label: "bangkok", type: "city", detail: "", apply: '"bangkok" ' },
    {
      label: "barcelona",
      type: "city",
      detail: "",
      apply: '"barcelona" ',
    },
    { label: "moscow", type: "city", detail: "", apply: '"moscow" ' },
    { label: "dubai", type: "city", detail: "", apply: '"dubai" ' },
    { label: "beijing", type: "city", detail: "", apply: '"beijing" ' },
    { label: "istanbul", type: "city", detail: "", apply: '"istanbul" ' },
    {
      label: "amsterdam",
      type: "city",
      detail: "",
      apply: '"amsterdam" ',
    },
    { label: "hanoi", type: "city", detail: "", apply: '"hanoi" ' },
    { label: "bangkok", type: "city", detail: "", apply: '"bangkok" ' },
    {
      label: "barcelona",
      type: "city",
      detail: "",
      apply: '"barcelona" ',
    },
    { label: "moscow", type: "city", detail: "", apply: '"moscow" ' },
    { label: "dubai", type: "city", detail: "", apply: '"dubai" ' },
    { label: "beijing", type: "city", detail: "", apply: '"beijing" ' },
    { label: "istanbul", type: "city", detail: "", apply: '"istanbul" ' },
    {
      label: "amsterdam",
      type: "city",
      detail: "",
      apply: '"amsterdam" ',
    },
    { label: "hanoi", type: "city", detail: "", apply: '"hanoi" ' },
    { label: "bangkok", type: "city", detail: "", apply: '"bangkok" ' },
    {
      label: "barcelona",
      type: "city",
      detail: "",
      apply: '"barcelona" ',
    },
    { label: "moscow", type: "city", detail: "", apply: '"moscow" ' },
    { label: "dubai", type: "city", detail: "", apply: '"dubai" ' },
    { label: "beijing", type: "city", detail: "", apply: '"beijing" ' },
  ],
  operators: [
    {
      label: "and",
      type: "operatorAnd",
      detail: "[and]",
      apply: "AND ",
    },
    {
      label: "or",
      type: "operatorOr",
      detail: "[or]",
      apply: "OR ",
    },
    {
      label: "not",
      type: "operatorNot",
      detail: "[not]",
      apply: "NOT ",
    },
  ],
  keywords: [
    {
      label: "sprinklr",
      detail: "[keyword]",
      type: "keyword",
      apply: "sprinklr ",
    },
    {
      label: "apple",
      detail: "[keyword]",
      type: "keyword",
      apply: "apple ",
    },
    {
      label: "banana",
      apply: "banana ",
      detail: "[keyword]",
      type: "keyword",
    },
    {
      label: "cat",
      detail: "[keyword]",
      type: "keyword",
      apply: "cat ",
    },
  ],
  advancedOperators: [
    {
      label: "city",
      detail: "[keyword]",
      type: "link",
      apply: "city: ",
    },
    {
      label: "country",
      detail: "[keyword]",
      type: "link",
      apply: "country: ",
    },
  ],
};
export default Data;
